version: "3.9"

services:
  weather-app:
    image: dbouraoui/weather-app:latest
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.weather.rule=Host(`signacore.fr`)"
        - "traefik.http.routers.weather.entrypoints=websecure"
        - "traefik.http.routers.weather.tls.certresolver=myresolver"
        - "traefik.http.services.weather.loadbalancer.server.port=3000"
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 256M